### ISSUE TITLE
Adding custom command generator

### ISSUE THREAD

**Issue by JadeMugs** [arminbro/generate-react-cli#42] opened 2021-03-14 22:13 UTC
I need to generate non-component files base on custom templates.

Based on the current docs, this is how I tried to add the command _actions_ to create action files and folders. 
```
// generate-react-cli.json
{
  "usesTypeScript": true,
  "usesCssModule": false,
  "cssPreprocessor": "None",
  "testLibrary": "None",
  "component": {
    "default": {
      "path": "src/components",
      "withStory": true,
      "withStyle": true,
      "withTest": false,
      "withLazy": false
    }
  },
  "action": {
    "default": {
      "path": "src/actions",
      "withIndex": true,
      "customTemplates": {
        "index": "src/templates/actions/index.tsx"
      }
    }
  }
}
```
Then running `npx generate-react-cli action Test` I expected to see the folder _Test_ with the file _index.tsx_ into _src/actions_.
At the moment, running this command throws an `error: unknown command 'action'`.

I also tried to add the configuration into `component.action` and run `npx generate-react-cli component Test --type=action` but the command generates default component files and I don't want them.

Think about adding custom generator command support or disable default files creation.

**Comment by arminbro** [comment] 2021-03-15 00:02
Hi @JadeMugs 

Your second approach is the right one, but you just need to make a minor adjustment in your `generate-react-cli.json` config file to make it work correctly.

> I also tried to add the configuration into component.action and run npx generate-react-cli component Test --type=action but the command generates default component files and I don't want them.

You'll need to remove the extra default field from your action component type. This is what you want to do in your `generate-react-cli.json` config file:
```json
{
  "usesTypeScript": true,
  "usesCssModule": false,
  "cssPreprocessor": "None",
  "testLibrary": "None",
  "component": {
    "default": {
      "path": "src/components",
      "withStory": true,
      "withStyle": true,
      "withTest": false,
      "withLazy": false
    },
    "action": {
      "path": "src/actions",
      "withIndex": true,
      "customTemplates": {
        "index": "src/templates/actions/index.tsx"
      }
    }
  }
}
```

Now you have two types of components you can generate. One is your `default` and the other one is your `action`.

You can generate a component with the `default` configurations without passing a `--type` flag like so:
`npx generate-react-cli component Test`

If you do want to use your `action` component type you run it like so:
`npx generate-react-cli component Test --type=action`

Hope this info was helpful. I'm going to close this ticket as not a bug. Let me know if you run into any other issues.

✌️

**Closed** 2021-03-15 00:02 UTC

**Comment by JadeMugs** [comment] 2021-03-15 00:20
This approch creates a _Test.tsx_ file (the default component file).
I tried to remove it adding _--withComponent=false_ to arguments but didn't work.

Is there a solution to solve the problem?

**Comment by arminbro** [comment] 2021-03-15 01:06
@JadeMugs 

I think I now understand what you're trying to do. GRC currently only supports generating components, but thankfully the command is fully customizable. 

You need to override the `action.customTemplates.component` instead of using `withIndex`. 

Update your GRC config file like this:
 ```json
{
  "usesTypeScript": true,
  "usesCssModule": false,
  "cssPreprocessor": "None",
  "testLibrary": "None",
  "component": {
    "default": {
      "path": "src/components",
      "withStory": true,
      "withStyle": true,
      "withTest": false,
      "withLazy": false
    },
    "action": {
      "path": "src/actions",
      "customTemplates": {
        "component": "src/templates/actions/index.tsx"
      }
    }
  }
}
```

GRC will use that file name that you have set in the config file (`action.customTemplates.component` ) and use it to generate your file.

Now you can run your command like this:
```
npx generate-react-cli component Test --type=action
```

Hopefully this gives you the result you're looking for.
